name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
      - run: flutter pub get
      - run: flutter test
      - name: Install Android NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends android-ndk
      - run: flutter build apk
